n = int(input())
*x, = map(int, input().split())
*y, = map(int, input().split())
print(sum([abs(x[i] - y[i]) for i in range(n)]))
print(sum([(x[i] - y[i])**2 for i in range(n)])**0.5)
print(sum([abs(x[i] - y[i])**3 for i in range(n)])**(1 / 3))
print(max([abs(x[i] - y[i]) for i in range(n)]))
